// sidebars-docs-02.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs02Sidebar: [{ type: "autogenerated", dirName: "." }],
};

module.exports = sidebars;
